export enum AuthErrorCode {
  EMAIL_EXISTS = 'AUTH.EMAIL_EXISTS',
  INVALID_CREDENTIALS = 'AUTH.INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'AUTH.TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID = 'AUTH.REFRESH_TOKEN_INVALID',
  USER_NOT_FOUND = 'AUTH.USER_NOT_FOUND',
  ACCESS_DENIED = 'AUTH.ACCESS_DENIED',
}
